server:
  port: 8086
  servlet:
    context-path: /api

springdoc:
  packages-to-scan:
    - com.impulso.impulsobackoffice.usuario.infrastructure.controllers
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    use-root-path: true

jwt:
  secret: "secret_key"

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: "Impulso BO: DEV"
  datasource:
    url: jdbc:postgresql://localhost:5432/impulso_test_2?stringtype=unspecified
    username: postgres
    password: coffee2sweet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE
        security:
          web:
            FilterChainProxy: DEBUG
      hibernate:
        SQL: DEBUG
