server:
  port: 8086
  servlet:
    context-path: /api/v1

springdoc:
  packages-to-scan:
    - com.impulso.impulsobackoffice.usuario.infrastructure.controllers
    - com.impulso.impulsobackoffice.departamento.infrastructure.controller
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: "secret_key"

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: "Impulso BO: DEV"
  datasource:
    url: jdbc:postgresql://localhost:5432/impulso_db_development?stringtype=unspecified
    username: postgres
    password: coffee2sweet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE
        security:
          web:
            FilterChainProxy: DEBUG
      hibernate:
        SQL: DEBUG
